<!DOCTYPE html>
<html lang='en'>
<head>
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Product",
  "name" : "Techwheel",
  "image" : "http://www.techwheel.org/images/logowheel.png",
  "description" : "Techwheel is largely concerned in building digitally transformed set of people who will contribute immensely to the future by influencing their community using technology.",
  "url" : "http://www.techwheel.org/",
  "brand" : {
    "@type" : "Brand",
    "name" : "TechWheel Foundation",
    "logo" : "http://www.techwheel.org/images/logo.png"
  },
  "review" : {
    "@type" : "Review",
    "author" : {
      "@type" : "Person",
      "name" : "Kayode Goodness"
    },
    "datePublished" : "2018-04-03 T15:30",
    "reviewRating" : {
      "@type" : "Rating",
      "ratingValue" : "5",
      "bestRating" : "5",
      "worstRating" : "0"
    },
    "reviewBody" : "Talents are built here. No better place to learn and build awesome stuffs than Techwheel"
  },
"potentialAction": [{
  "@type": "SearchAction",
  "target": "http://techwheel.org/search?q={search_term_string}",
  "query-input": "required name=search_term_string"
}]
}

{
  "@context": "http://schema.org",
  "@type": "Organization",
  "url": "http://www.techwheel.org",
  "logo": "http://www.techwheel.org/images/logowheel.png",
  "image" : "http://www.techwheel.org/images/logowheel.png",
    "sameAs": [
    "http://www.facebook.com/techwheelorg",
    "http://instagram.com/techwheelorg",
    "https://twitter.com/techwheelorg",
    "https://medium.com/techwheel"
  ],
  "openingHoursSpecification": [
  {
    "@type": "OpeningHoursSpecification",
    "dayOfWeek": "Saturday",
    "opens": "00:00",
    "closes": "23:59"
  },
  {
    "@type": "OpeningHoursSpecification",
    "dayOfWeek": "Sunday",
    "opens": "00:00",
    "closes": "00:00"
  }
]
}

{
  "@context": "http://schema.org",
  "@type": "NewsArticle",
  "headline":"Techwheel Stories",
  "image": [
    "http://www.techwheel.org/images/logowheel.png"
   ]

  }

</script>


	<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-117542892-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-117542892-1');
</script>

	<meta class="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<title>Techwheel (Human Development Platform)</title>
	  <meta name="description" content="Techwheel is largely concerned in building digitally transformed set of people who will contribute immensely to the future by influencing their community using technology.">
	  <meta name="google-site-verification" content="jmBwMF6BE1PthICqafGyywWlbq5BRb3ZEpIetelvZuA" />
        <meta name="author" content="Techwheel">
        <meta name="twitter" content="@techwheelorg" />
        <meta name="instagram" content="@techwheelorg" />

        <meta property="og:type" content="website" />
        <meta property="og:title" content="TechWheel - Advancing human development via technology" />
        <meta property="og:description" content="Techwheel is largely concerned in building digitally transformed set of people who will contribute immensely to the future by influencing their community using technology." />
        <meta property="og:url" content="https://techwheel.com/" />
        <meta property="og:site_name" content="Techwheel" />
        <meta property="og:image" content="http://www.techwheel.com/images/logo.png" />
        <meta property="og:image:secure_url" content="http://www.techwheel.com/images/logo.png" />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:creator" content="@techwheelorg" />
        <meta name="twitter:description" content="Techwheel is largely concerned in building digitally transformed set of people who will contribute immensely to the future by influencing their community using technology." />
        <meta name="twitter:title" content="TechWheel - Advancing human development via technology" />
	<link rel="shortcut icon" href="images/logo.png" />
	<link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
	<!-- Don't forget to add your metadata here -->
	<link rel='stylesheet' href='css/style.min.css' />

	<!-- Start of Async Drift Code -->
		<script>
		!function() {
		  var t;
		  if (t = window.driftt = window.drift = window.driftt || [], !t.init) return t.invoked ? void (window.console && console.error && console.error("Drift snippet included twice.")) : (t.invoked = !0,
		  t.methods = [ "identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on" ],
		  t.factory = function(e) {
		    return function() {
		      var n;
		      return n = Array.prototype.slice.call(arguments), n.unshift(e), t.push(n), t;
		    };
		  }, t.methods.forEach(function(e) {
		    t[e] = t.factory(e);
		  }), t.load = function(t) {
		    var e, n, o, i;
		    e = 3e5, i = Math.ceil(new Date() / e) * e, o = document.createElement("script"),
		    o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "https://js.driftt.com/include/" + i + "/" + t + ".js",
		    n = document.getElementsByTagName("script")[0], n.parentNode.insertBefore(o, n);
		  });
		}();
		drift.SNIPPET_VERSION = '0.3.1';
		drift.load('83xznd5y9zps');
		</script>
		<!-- End of Async Drift Code -->

		<script id="mcjs">!function(c,h,i,m,p){m=c.createElement(h),p=c.getElementsByTagName(h)[0],m.async=1,m.src=i,p.parentNode.insertBefore(m,p)}(document,"script","https://chimpstatic.com/mcjs-connected/js/users/72b2713a22ccb0ff0c4325bd9/2833743144843989db919b447.js");
		</script>
</head>
<body>
	<!-- Hero(extended) navbar -->
	<div class="navbar navbar--extended" data-aos="fade-down">
		<nav class="nav__mobile"></nav>
		<div class="container">
			<div class="navbar__inner">
				<a href="/" class="navbar__logo"><img height="52dp" src="images/logowheel.png" /></a>
				<nav class="navbar__menu">
					<ul>
						<li><a href="#about">About Us</a></li>
						<li><a href="#contact">Contact Us</a></li>
						<li><a href="mentor">Our Mentors</a></li>
						<li><a href="https://www.medium.com/techwheel" target="_blank">Our Stories</a></li>
					</ul>
				</nav>
				<div class="navbar__menu-mob"><a href="" id='toggle'><svg role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z" class=""></path></svg></a></div>
			</div>
		</div>
	</div>
	<!-- Hero unit -->
	<div class="hero" data-aos="fade-down">
		<div class="hero__overlay hero__overlay--gradient"></div>
		<div class="hero__mask"></div>
		<div class="hero__inner">
			<div class="container">
				<div class="hero__content">
					<div class="hero__content__inner" id='navConverter'>
						<h1 class="hero__title">We <span id="typedit" style="border-bottom:3px solid #06D19C;" ></span >using<p> technology</p></h1>
						<p class="hero__text">We are largely concerned in building digitally transformed set of people who will contribute immensely to the future by influencing their community using technology.</p>
						<a target="_blank" href="https://goo.gl/forms/EQtAcqeKEcMFQqJw1" class="button button__accent">Apply to Join</a>
						<a target="_blank" href="https://goo.gl/forms/PQJx7ErJfnT7K3KO2" class="button hero__button">Volunteer | Partner with Us</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="hero__sub">
		<span id="scrollToNext" class="scroll">
			<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" class='hero__sub__down' fill="currentColor" width="512px" height="512px" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve"><path d="M256,298.3L256,298.3L256,298.3l174.2-167.2c4.3-4.2,11.4-4.1,15.8,0.2l30.6,29.9c4.4,4.3,4.5,11.3,0.2,15.5L264.1,380.9c-2.2,2.2-5.2,3.2-8.1,3c-3,0.1-5.9-0.9-8.1-3L35.2,176.7c-4.3-4.2-4.2-11.2,0.2-15.5L66,131.3c4.4-4.3,11.5-4.4,15.8-0.2L256,298.3z"/></svg>
		</span>
	</div>
	<!-- Steps -->
	<div class="steps landing__section" data-aos="fade-up">
		<div class="container" data-aos="fade-down">
				<a name="about" style="height: 0px;"></a>
			<h2>Who we are?</h2>
			<p>Here are the things that keeps us awake and drives us at Tech Wheel Foundation.</p>
		</div>
		<div class="container">
			<div class="steps__inner">
				<div class="step" data-aos="fade-down">
					<div class="step__media">
						<img src="./images/stars.svg" class="step__image">
					</div>
					<h4>Our Vision</h4>
					<p class="step__text">To build a community of digitally oriented people who will drive innovations and build the future.</p>
				</div>
				<div class="step" data-aos="fade-down">
					<div class="step__media">
						<img src="./images/mission.svg" class="step__image">
					</div>
					<h4>Our Mission</h4>
					<p class="step__text">We constantly invest in human development by identifying talent, grooming them and deploying them as a solution driven technocrats to their community.</p>
				</div>
				<div class="step" data-aos="fade-down">
					<div class="step__media">
						<img src="./images/secure.svg" class="step__image">
					</div>
					<h4>Our Core Values</h4>
					<p class="step__text">Committed to seeing life transformed digitally as we believe that digital oriented people will birth the future.</p>
				</div>
			</div>
		</div>
	</div>
	<!-- Expanded sections -->

	<div class="expanded landing__section" data-aos="fade-down">
		<div class="container">
			<div class="expanded__inner">
				<div class="expanded__media">
					<img src="./images/transformed.svg" class="expanded__image">
				</div>
				<div class="expanded__content" data-aos="fade-down">
					<h2 class="expanded__title">Our Approach</h2>
					<p class="expanded__text">We pick up motivated people (young and old) and take them through the swift refinement processes of being skilled in tech-related things via the help of our Resource persons (TechWheel Mentors) who are actively invloved within the innovation space.</p>
				</div>
			</div>
		</div>
	</div>
<div class="expanded landing__section" data-aos="fade-down">
		<div class="container">
			<div class="expanded__inner">
				<div class="expanded__media" data-aos="zoom-in-up">
					<img src="./images/mentors.svg" class="expanded__image">
				</div>
				<div class="expanded__content" data-aos="fade-down">
					<h2 class= "expanded__title"> Our End Product</h2>
					<p class="expanded__text">At Tech Wheel Foundation, We do not only transform people digitally, We also empower and deploy them as soldiers into the tech ecosystem by granting them access to work with companies doing amazing stuffs, and as well helping them build a 21st century businesses that solves local problems in a global way.</p>
				</div>
			</div>
		</div>
	</div>
<!-- Our Team -->
	<div class="steps landing__section" data-aos="fade-up">
		<div class="container" data-aos="fade-down">
				<a name="about" style="height: 0px;"></a>
			<h2>TechWheel Team</h2>
			<p>Below are the young vibrants industrious innovators who are leading the Techwheel team</p>
		</div>
		<div class="container">
			<div class="steps__inner">
				<div class="step" data-aos="zoom-in-down">
					<div class="step__media">
						<img height="120dp" class="button hero__button" src="./images/tolu.png" class="step__image">
							<a href="https://linkedin.com/in/adetuyitolu" target="_blank">
								<h4 style="margin:0px;" >Adetuyi Tolu Emmauel</h4>
							</a>
					</div>

				</div>
				<div class="step" data-aos="zoom-in-down">
					<div class="step__media">
						<img height="120dp" class="button hero__button" src="./images/lanre.png" class="step__image">
						<a href="https://www.linkedin.com/in/ogungbelanre/" target="_blank">
							<h4 style="margin:0px;">Ogungbe Olanrewaju</h4>
						</a>
					</div>

				</div>
				<div class="step" data-aos="zoom-in-down">
					<div class="step__media">
						<img height="120dp" class="button hero__button" src="./images/david.png" class="step__image">
							<a href="https://www.linkedin.com/in/obiebukadavid/" target="_blank">
								<h4 style="margin:0px;">Obi Ebuka David</h4>
							</a>
					</div>


				</div>
			</div>
		</div>
	</div>

	<!-- Call To Action -->
	<div class="cta cta--reverse">
		<div class="container" align="center">
			<div class="cta__inner" data-aos="zoom-in-down">
				<h2 class="cta__title">Subscribe to our NewsLetter</h2>
				<p class="cta__sub cta__sub--center">Be among the first set of people to get notified of our amazing works.</p>
				<!--<a href="#" class="button button__accent">Notify Me</a>-->
			</div>
			<form data-aos="fade-up"  class="form container" role="form"  action="https://techwheel.us17.list-manage.com/subscribe/post?u=72b2713a22ccb0ff0c4325bd9&amp;id=d5e6ba1aae" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form"class="validate" target="_blank" novalidate>
                <div class="form-group" style="margin-right: 10px; display: inline;">
                    <input style="display: inline; width: 250px; " type="email" name="EMAIL"  id="mce-EMAIL"class="form-control transparent" placeholder="Your email here..." required>

                </div>
                <div  style="display: inline;">
                    <button  type="submit" class="button button__accent" name="subscribe" id="mc-embedded-subscribe" >Notify Me
					</button>
				</div>

                <div id="mce-responses" class="clear">
					     <div class="response" id="mce-error-response" ></div>
					     <div class="response" id="mce-success-response" style="display:none"></div>
				</div>
				<div style="position: absolute; left: -5000px;" aria-hidden="true">
					<input type="text" name="b_05e4d9a106bc39f2f2ceb1684_b750a566c7"tabindex="-1" value="">
				</div>
             </form>
		</div>
	</div>
	<!-- Footer -->
	<div class="footer footer--dark">
		<div class="container">
			<a name="contact"></a>
			<div class="footer__inner">
				<div class="footer__data">
					<div class="footer__data__item">
						<div class="footer__row">
							<a href="index.html" class="footer__textLogo">Tech Wheel Foundation</a>
						</div>
						<div class="footer__row" style="width: 220px;">
            No 3, St. Finbarr's College Road, Akoka-Yaba, Lagos.
						</div>
					</div>

				</div>
				<div class="footer__data">
					<div class="footer__data__item">

						<div class="footer__row">
							<a href="index.html" class="footer__textLogo">Reach out to Us</a>
						</div>
					  <div class="footer__row">
					 	training@techwheel.org
					   </div>

					</div>

					<div class="footer__data__item">
				<div class="footer__row">
							<a href="index.html" class="footer__textLogo">Our Social Media</a>
						</div>
					<div class="footer__row">
						<a href="https://twitter.com/techwheelorg" target="_blank" class="footer__link">Twitter</a> |
						<a href="https://www.facebook.com/techwheelorg" target="_blank" class="footer__link">Facebook</a> |
						<a href="https://www.medium.com/techwheel" target="_blank" class="footer__link">Medium</a>
					</div>
				</div>
					<div class="footer__data__item">
						<div class="footer__row">

							&copy 2018, All rights reserved
						</div>
					</div>

			</div>
		</div>
	</div>
<script src='js/app.min.js'></script>
<script src="js/typed/typed.min.js"></script>
 <script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script>
<script type='text/javascript'>
(function($) {
	window.fnames = new Array();
	window.ftypes = new Array();
	fnames[0]='EMAIL';
	ftypes[0]='email';
	fnames[1]='FNAME';
	ftypes[1]='text';
	fnames[2]='LNAME';
	ftypes[2]='text';
	fnames[3]='ADDRESS';
	ftypes[3]='address';
	fnames[4]='PHONE';
	ftypes[4]='phone';
	fnames[5]='BIRTHDAY';
	ftypes[5]='birthday';
}(jQuery));var $mcj = jQuery.noConflict(true);</script>
   <script>
            AOS.init({
            offset: 100,
            duration: 1500,
            easing: 'ease',
            delay: 300,
            once: true,
            });
        </script>
        <script type="text/javascript">
        var typed = new Typed(
            '#typedit', {
                strings: ["believe poverty can be defeated", "invest in Human Development","build innovators","build digital disruptors","educate people to start", "increase the number of people", "solve local and global problems"],
                typeSpeed: 100,
                fadeOut: true,
                smartBackspace: true,
                backDelay: 3000,
                loop: true
            });
    </script>
</body>
</html>
